### ISSUE TITLE
Tabbar shifting down after scrolling, switching tabs and returning to scrolled view

### ISSUE THREAD

**Issue by emadd** [uias/Tabman#116]
I'm not sure if this issue is rooted in your project or in the parent view controller class [(MxParallaxHeader)](https://github.com/maxep/MXParallaxHeader) but I thought I'd reach out anyway and see if you might be able to help.

Here's my view hierarchy...

UINavigationController
-- MXScrollViewController
---- Header View Controller
---- TabmanViewController

It looks and behaves very nicely (A) until I leave a scrolled tab in a scrolled position (B), navigate to a new tab and then navigate back to the scrolled tab (C).  The tabbar appears to be shifting down exactly as high as the navigation bar.

![A](https://user-images.githubusercontent.com/240649/28073316-59915ade-6623-11e7-9cec-929e0c262d4e.png)

![B](https://user-images.githubusercontent.com/240649/28073322-5e452524-6623-11e7-8f2b-0e36abc5b75a.png)
 
![C](https://user-images.githubusercontent.com/240649/28073329-63cfdc8c-6623-11e7-9d69-d86d254e2567.png)

**Comment by msaps** [comment]
Looks like it could be a problem with Tabman.. 

From first glance I think it'll be an issue with the bar being inset incorrectly again after view layout. 

I'll try and take a look at implementing Tabman with MXParallaxHeader and see what I can find and get it fixed 👍

**Comment by msaps** [comment]
@emadd would you be able to provide a demo project with your view hierarchy that displays the issue? Would be really appreciated! 😄

**Comment by emadd** [comment]
I can pull one together this evening

**Comment by msaps** [comment]
@emadd thanks that would be great!

**Comment by emadd** [comment]
[Here You Go](https://github.com/emadd/TabmanParallaxDemo)

The content in the tabs doesn't even have to vertically scroll to cause the bar to shift down.  All you have to do is switch tabs.

**Comment by msaps** [comment]
@emadd thanks for that! 

I've had a quick play, and think I've managed to figure out a solution which doesn't require a change in either component. 

The issue that was causing the bar to shift was because it's pinned to the `topLayoutGuide` of the view controller, which had a `length` of 0 on initial layout, but then updates to the height of the system bars on scroll causing the jump.

I suspect this is due to some UIKit oddity, or the fact that `MXParallaxHeader` uses ManualLayout which wasn't playing too nicely with the AutoLayout in Tabman. 

**But anyway the fix!**

I added an additional container view controller which acts as the `scroll view controller` for the `MXScrollViewController`.  The `TabmanViewController` is then the child of this container:

![screen shot 2017-07-13 at 10 51 21](https://user-images.githubusercontent.com/3515448/28160814-3fc7c3f8-67b9-11e7-841e-156f8526834d.png)

**Hierarchy**

- `MXScrollViewController`
     - `Header View Controller` (parallax header)
     - `Tabman Container View Controller` (scroll view controller)
          - `TabmanViewController`

I've updated the demo application you provided with the fix:

[TabmanParallaxDemo-fixed.zip](https://github.com/uias/Tabman/files/1144735/TabmanParallaxDemo-master.zip)

Let me know how you get on! 👍

**Comment by emadd** [comment]
Confirmed!  Thank you.

**Comment by emadd** [comment]
Sorry, but this has come up again for me.  It seems that it only happens when the pages are scrolled/swiped left to right.  It's very inconsistent, but the solution you thought was final is not.  For now, I'm disabling the side-to-side scrolling.

**Comment by emadd** [comment]
iOS 11 makes the aforementioned workaround moot

**Comment by msaps** [comment]
@emadd is this resolved in the latest versions of Tabman? Done quite a bit of work with the insetting logic in the last couple of updates.

**Comment by emadd** [comment]
@msaps I had to switch to another library.  My particular use case is probably an outlier, so feel free to close this.  FWIW: I ended up using a library made by the same folks who created MXParallaxHeader and the two are interoperable.

**Comment by ugenlik** [comment]
@emadd What did you end up using?  I have a very similar problem.
