### ISSUE TITLE
Custom height of tabbar

### ISSUE THREAD

**Issue by Quangna** [uias/Tabman#133]
How i can custom height of tabman. i following this code:
`appearance.layout.height = .explicit(value: 30)`

but nothing to change

**Comment by msaps** [comment]
@Quangna please check out this [issue](https://github.com/uias/Tabman/issues/126#issuecomment-321194291) which details why you are probably seeing the bar not compress to your desired height. 👍

**Comment by annjawn** [comment]
So i have a button at the bottom of the ViewController which I want to stick above the tabman tab bar, the problem is I don't know what the height of the tab bar is. How do I find out what the current height of my tab bar is so that I can use autolayout to constraint my button from the bottom edge of the VC so that it doesn't get hidden by the tab bar? I am not using any custom height for the tab bar.

**Comment by msaps** [comment]
@annjawn you should be able to get the current height of the tab bar by looking at `TabmanViewController.bar.requiredInsets` and reading the `.bar` property. This will give you a `CGFloat` which corresponds to the height of the bar.
