### ISSUE TITLE
How to distribute equally the items title?

### ISSUE THREAD

**Issue by Lulli4444** [uias/Tabman#159]
Hi, I have different Tabman control in my app, sometimes with 3 items, or 4 or 5. I want to distribute them in the bar equally. So far I have found only the .leftAligned and .centered properties, but they don't distribute the titles. How can I managed this behaviour? Thanks

**Comment by Mohammed-Eliass** [comment]
Any ideas ?

**Comment by msaps** [comment]
@Lulli4444 @Mohammed-Eliass 

This layout isn't quite available in the `.scrollingButtonBar` style, as by default the items just size to their required width and are stacked in such a way. One way to get around this would be to set a custom `minimumItemWidth` so that all items have to be a particular (equal) width?

If you have a smaller amount of bar items that won't require scrolling, you could also use the `.buttonBar` style as this will equally distribute the items in the available screen width by default.

**Comment by Mohammed-Eliass** [comment]
@msaps Thanks for clarification, I would do something like this if there are 2 tabs :
            bar.appearance = TabmanBar.Appearance({ (appearance) in {
                        appearance.layout.itemDistribution = TabmanBar.Appearance.Layout.ItemDistribution.leftAligned
                        appearance.layout.minimumItemWidth = UIScreen.main.bounds.width / 2
                        appearance.layout.interItemSpacing = 0.0
                        appearance.layout.edgeInset = 0.0
            }

I think this will solve the problem 👍 
And thanks for your amazing lib 🥇

**Comment by msaps** [comment]
@Mohammed-Eliass you could do that, or you could just simply set `bar.style = .buttonBar` and that would give you the equally distributed layout.

**Comment by Lulli4444** [comment]
Thanks, I will try with the .buttonBar!

**Comment by ratala1** [comment]
.style or . appearance are not available in version 2.4. @msaps how do i make the buttons have equal width? I am using TMBar.ButtonBar()

**Comment by ealeksandrov** [comment]
This worked for me:
```swift
let bar = TMBar.ButtonBar()
bar.layout.contentMode = .fit
```
