### ISSUE TITLE
How to use forward direction?

### ISSUE THREAD

**Issue by yashdishatechnology** [uias/Tabman#166]
i am using tabman and i want to use only forward direction in scrolling.Please Help me

**Comment by yashdishatechnology** [comment]
Any there for help.I am using tabman for dynamically adding tabs.Like adding tabs when user clicks on last tab.when i scroll first tab to next tab it activates neutral direction and the from second to this it activates reverse direction.My question is to how to activate forward direction.Please Help.

**Comment by msaps** [comment]
@yashdishatechnology this is unfortunately not possible, due to the way that `UIPageViewController` handles it's internal scroll view you can't use direction locking. The only way to lock a user into only being able to go a certain direction would be by disallowing the scroll behaviour and using animated page scrolling.
