### ISSUE TITLE
Tabman does not layout views below bar

### ISSUE THREAD

**Issue by OskarGroth** [uias/Tabman#180]
Using the Demo and enabling Safe Area layout guides, with content at the top of a child view that is not a scroll view:

![skarmavbild 2017-11-13 kl 16 14 04](https://user-images.githubusercontent.com/1417019/32732707-b6acab0c-c88d-11e7-8e04-cbbd718ee3d6.png)

The content ends up being obscured by the bar:

![skarmavbild 2017-11-13 kl 16 09 05](https://user-images.githubusercontent.com/1417019/32732829-fc2143aa-c88d-11e7-9608-bf602e824991.png)

It seems it is not possible to layout the content below the Tabman bar, at least not without having every child view be explicitly aware of the tab bar in it's superview. This should be possible, and perhaps similar to the behaviour of `UINavigationBar` where the `translucent` setting can control whether content is laid out below or beneath the bar.

**Comment by msaps** [comment]
@OskarGroth Hi,

Currently, the only form of automatic insetting that is available is when you are using a `UIScrollView` or something like a `UITableViewController`. 

However, I have just taken a look at `additionalSafeAreaInsets` which does seem to offer the desired behaviour when running on iOS 11. Unfortunately I don't think this functionality can be made backwards compatible, as far as I know all the layout guides / margins are not mutable for the root `view` of a `UIViewController`.

I will add support for `additionalSafeAreaInsets` as soon as possible so that at least on iOS 11, non scrollable content will be insetted correctly 👍

**Comment by OskarGroth** [comment]
Thanks for looking into this. Supports for `additionalSafeAreaInsets` would be perfect.

**Comment by msaps** [comment]
@OskarGroth this is now available in [1.0.7](https://github.com/uias/Tabman/releases/tag/1.0.7) 😄

**Comment by sasojadrovski** [comment]
Hey @msaps,

This looks fine in 1.0.7. I have noticed a `print` statement that looks like it's used for debugging purposes online. 
It is located in `TabmanViewController+Insetting.swift` at line 127.

Is this intentionally left here?

Cheers!

**Comment by msaps** [comment]
@sasojadrovski nope definitely a mistake! Will get that taken out and push a new update 😅

**Comment by sagar230** [comment]
![Screenshot 2019-09-18 at 4 21 55 PM](https://user-images.githubusercontent.com/55526401/65216763-a1d9c600-dacf-11e9-82fe-52a783ae2187.png)
![Screenshot 2019-09-18 at 4 22 09 PM](https://user-images.githubusercontent.com/55526401/65216764-a2725c80-dacf-11e9-842f-8eae121e4bd2.png)

Please help me with the bar in Tabman .. I can't set the bar to the length of the title ..
