### ISSUE TITLE
Internal access prohibits certain types of extensions

### ISSUE THREAD

**Issue by robcecil** [uias/Tabman#201]
### New Issue Checklist

- [x ] Updated Tabman to the latest version
- [x ] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x ] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

In prior versions of Tabman, a class deriving from TabmanViewController had access to self.tabmabBar; now that property is internal. 

I need access in order to attach a gesture recognizer.

I've looked at both:

1. self.attach(...) to attach a external TabmanBar.
2. Custom tabmanBar.

Both seem cumbersome, considering I only want access to the tabmanBar in the viewcontroller.

**Comment by robcecil** [comment]
Exacerbating the issue, I tried looking at #2 (custom tabmanbar) ... I need essentially TabmanScrollingButtonBar, so I tried creating a new class to derive from that, boom... internal.

**Comment by msaps** [comment]
@robcecil I'm currently planning/underway with redesigning the bar framework. As it is not that useful for extending on, and the current design is becoming problematic for adding new features. 

Unfortunately there is no quick fix for your issue without manually changing the access permissions, but I will make sure to improve the permissions and think of such use cases in v2.0

**Comment by msaps** [comment]
@robcecil took a bit (a lot) of time, but [Tabman 2](https://github.com/uias/Tabman/releases/tag/2.0.0) is now available and much improved in terms of customisation and extensibility. 🎉 

Will close this 😄

**Comment by CodeCommander** [comment]
This appears to still be a problem in version 2.1 .

I was unable to just subclass TMConstrainedHorizontalBarLayout or TMHorizontalBarLayout because of internal members stackView and layout(parent: TMBarLayoutParent, insetGuides: TMBarLayoutInsetGuides). 

Then I used your TinderBar example as a guide and was unable to use those because of internals like UIColor.interpolate extension.

I'm also unable to extend TMLabelBarButton because it is final and I'm unable to reuse it's code in my own module because AnimateableLabel is internal to Tabman.

Am I misunderstanding the manner in which I should be customizing the layout and buttons? It seems like these classes should all be openly extendable by external modules.
