### ISSUE TITLE
Create bar with top padding

### ISSUE THREAD

**Issue by NBibikov** [uias/Tabman#283]
### New Issue Checklist

- [x] Updated Tabman to the latest version
- [x] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description
Hello! Thanks for nice library. 
How i can create bar with top margin? I need place content before bar, but cann't find decision for it.
With 'embedBar(in:'  i must manage top padding for child vc, and i think this is not best solution.

**Comment by msaps** [comment]
@NBibikov not too sure I can envisage what you want.. But if you are wanting to insert custom views above the bar or anything like this, I'd recommend using the bar embedding functions. Tabman is only designed to support 'simple' layouts consisting only of the bar.

**Comment by NBibikov** [comment]
Yes, I need place content above bar. And if I understand correct I can do that in 2 way:
1) place some view for bar in storyboard and use 'embedBar(in:' function. In this variant child controllers has full height of screen and not start under bar. How I can fix that?
2) maybe i can use bar with .top portion and use some padding for add padding for bar. In this case I don't need manage height for child's vc. Can I use top padding for bar position?

![screen shot 2018-05-01 at 2 51 10 pm2](https://user-images.githubusercontent.com/8437488/39472108-d68482a0-4d4f-11e8-8195-5017e3e6d6d0.png)
![screen shot 2018-05-01 at 2 50 11 pm2](https://user-images.githubusercontent.com/8437488/39472109-d69fa760-4d4f-11e8-99d5-34a48dd75da5.png)
[UpdateTitles.zip](https://github.com/uias/Tabman/files/1963678/UpdateTitles.zip)

**Comment by ahmedsafadii** [comment]
@msaps same here can we do this ?

**Comment by msaps** [comment]
@NBibikov @ahmedsafadii I would advise as you have mentioned to use the `embedBar()` function as this is a custom layout from Tabman's point of view. This will disable the auto insetting engine, which is why you are seeing the child contents taking up the entire screen. 

Tabman provides insetting values that can be used for insetting your child content manually (in addition to your custom view hierarchy positional values). See here - [Child Content Insetting](https://github.com/uias/Tabman#child-content-insetting). 

Unfortunately there isn't really a way for Tabman to be able to account for all these custom scenarios reliably, thus the strict functionality of the AutoInsetting engine.

**Comment by ahmedsafadii** [comment]
@msaps for me i just want create view about the tabs it's possible and how !?

**Comment by msaps** [comment]
@ahmedsafadii you would create your custom view hierarchy as desired and then use the `embedBar()` function to embed the bar in a custom container view. As mentioned this will disable auto insetting so you will have to inset your child content manually using the methods described above.

**Comment by ahmedsafadii** [comment]
@msaps if there's example for it :(

**Comment by NikitaSkripchenko** [comment]
any updates on this?

**Comment by techinpark** [comment]
@msaps any document for this?

**Comment by ahmedsafadii** [comment]
@msaps
