### ISSUE TITLE
TableView not scrolling to top on Load if tabman menu exists

### ISSUE THREAD

**Issue by Sinan-Noureddine** [uias/Tabman#316]
After implementing library. I added a table view in the childViewController. Everything works fine except that on launching the view. The Table view wouldn't be scrolled to top. Please check attached images.

Any idea why this is happening?

![ad6a81c7-d847-4599-866e-823a70fa99a4](https://user-images.githubusercontent.com/22674620/43466835-1c71684c-94e9-11e8-8290-2783f87f770c.jpeg)

**Comment by msaps** [comment]
@Sinan-Noureddine looks like something with the insetting, will check it out

**Comment by nizarmah** [comment]
Hello,

I was looking into this recently, as I am working with Sinan on the application...
I opened the AutoInsetter.swift and changed those lines (starting from line 62)...

```
// if isTopInsetChanged {
if true {
    var contentOffset = scrollView.contentOffset
    // contentOffset.y -= topInsetDelta
    contentOffset.y = 0
    scrollView.contentOffset = contentOffset
}
```

And surprisingly, it fixed the issue.

So, I was wondering, is there any way to give custom offsets instead of them being computed automatically ?
This might not be the best solution; however, I am very new to iOS development and have no other suggestion, sorry.

Have a great day!

**Comment by msaps** [comment]
@Sinan-Noureddine @nizarmah unfortunately I don't think the fix will be quite that easy 😅 This should be handled completely automatically.

If you can provide me with a demo project that makes this easily reproducible that would be really helpful! 👍

**Comment by nizarmah** [comment]
You are right, it should be handled automatically... Alright, I don't mind giving you permission to read the repository to solve the issue; however, I don't have permission to do that, so I'll discuss this with Sinan.

Thanks for your time.

**Comment by msaps** [comment]
@nizarmah I don't need permission to read the repo - a simple extraction/abstraction of the view controller that displays the issue would more than sufficient 😄

**Comment by Sinan-Noureddine** [comment]
@msaps lol it's fine i already pushed a testing app for the library and it has the same issue.

Please check:

https://github.com/Sinan-Noureddine/tabman-testing

**Comment by msaps** [comment]
@Sinan-Noureddine @nizarmah please try updating to AutoInsetter [1.2.6](https://github.com/uias/AutoInsetter/releases/tag/1.2.6) - it should fix the issue.

Note: it was caused because the `UITableView` was constrained to the safe area rather than the superview. In the [Troubleshooting](https://github.com/uias/Tabman/blob/master/Docs/TROUBLESHOOTING.md#2-check-your-constraints) docs I recommend constraining to the superview. 😄

**Comment by nizarmah** [comment]
Alright, thanks a lot! 

Will change the constraining to the superview.

Have a great week.

**Comment by msaps** [comment]
@nizarmah you shouldn't need to now with the update - but glad to have it fixed anyway 😄
