### ISSUE TITLE
How to reload pages and bar?

### ISSUE THREAD

**Issue by omidgolparvar** [uias/Tabman#335]
### Issue Description
I want to change `viewControllers` and reload TabMan. `self.reloadPages()` will reload pages, but the TabManBar will NOT change.

How can I fix this?

**Comment by omidgolparvar** [comment]
I found the solution.
Thanks.

**Comment by otymartin** [comment]
@omidgolparvar What is the solution?

**Comment by otymartin** [comment]
@msaps I guess this is it
``` bar.reloadData(at: 0...(barItems.count - 1), context: .full)```

I must say though that first parameter is very unfriendly :( - Any way it can be simplified with some default use cases like taking an enumeration eg: `reloadData(at: indexes: .all)` and then of course the more specific `reloadData(at: indexes: .range(ClosedRange<Int>)`

**Comment by msaps** [comment]
@otymartin `reloadData` is the only reload function currently available that is designed to reload the page view controller and also bars.

The `TMBar` reload function could also be used to reload a bar's contents - but this was more designed for the bar being used in a custom situation outside of `Tabman`. But yeah I could clean up the API. 

What are your requirements for reloading just out of interest (inc. dynamic items) - I'm adding support for this in the next version of TM 🎉 - setting images / titles / badges dynamically etc.

**Comment by otymartin** [comment]
@msaps Interesting because `reloadData()` was only reloading my `viewControllers` not my `barItems` I had to explicitly make the `bar.reloadData` call.

My currently use case is in form fields. I have fields for banking and depending a user's Country, different fields will populate, a determination I make at `viewDidLoad`. I think it works well for now I wouldn't add anything much more personally. 

`TM 🎉 - setting images / titles / badges dynamically etc`.
 As for this I did play around with TinderBar and have some interpolation behaviour + dynamic badge behaviour I would love to see. I will open a new feature request issue for it.

![fullsizerender](https://user-images.githubusercontent.com/2222881/53588004-da2cad80-3b59-11e9-9cb7-637dbc477f84.jpeg)

**Comment by otymartin** [comment]
`Interesting because `reloadData()` was only reloading my `viewControllers` not my `barItems` I had to explicitly make the `bar.reloadData` call```

I apologize, I implemented `PageboyViewControllerDelegate` without calling `super` implementation. You can shoot me now :(

**Comment by msaps** [comment]
@otymartin haha phew! 

Please do open feature requests! 2.2.0 will have dynamic items and also support for badging so anything else! TM 2.x is much easier to iterate on than previously 😅
