### ISSUE TITLE
Swift header not created with Carthage

### ISSUE THREAD

**Issue by tate-sa** [uias/Tabman#574]
### New Issue Checklist

- [X] Updated Tabman to the latest version
- [X] I took a look at the [Troubleshooting Guide](https://github.com/uias/Tabman/blob/main/Docs/Troubleshooting.md)
- [X] I searched for [existing GitHub issues](https://github.com/uias/Tabman/issues)

### Issue Description

I am updating to the newest version of Tabman in a ObjC & Swift project. I am running the following Carthage command to pull in the dependency:
carthage update --platform iOS --use-xcframeworks

My cartfile includes:
github "uias/Tabman"

This correctly pulls in Pageboy, creates both Pageboy.xcframework and Tabman.xcframework files, however Xcode can't find TabmanViewController in the auto generated <project>-Swift.h when compiling.

It looks like the Tabman-Swift.h file isn't being created by Carthage:
 - in Carthage/Build/Pageboy.xcframework/<architecture>/Pageboy.framework/Headers there is a Pageboy-Swift.h
 - but in the equivalent Tabman.xcframework directory there isn't a Tabman-Swift.h file, just a Tabman.h

**Comment by msaps** [comment]
Just had a look into this - didn't realise Carthage had added support for XCFrameworks finally!

Attached a quick demo project that I used to test it - everything seems to work, though I did get some log outputs about duplicated symbols...

This is using Xcode 12.5 and Carthage 0.38.0...

(Doesn't include the `Carthage` directory due to attachment size - but `carthage bootstrap --platform iOS --use-x
cframeworks` should do the trick).
[TabmanCarthage.zip](https://github.com/uias/Tabman/files/6488887/TabmanCarthage.zip)

<img width="1065" alt="Screenshot 2021-05-16 at 10 30 56" src="https://user-images.githubusercontent.com/3515448/118390893-cf26a080-b631-11eb-871d-753fb0e17136.png">

This is likely due to the way that Carthage is building the XCFrameworks
