### ISSUE TITLE
Viewcontroller add Tableview，have space

### ISSUE THREAD

**Issue by hb852143** [uias/Tabman#66]
Hello,
First time loading , tabview have space , like image
![img_0736](https://cloud.githubusercontent.com/assets/16014479/25735107/6baec042-319b-11e7-995c-4bf49ee2a814.PNG)
When I scroll tableview or swipe tab  , tableview space disappear , like image
![img_0737](https://cloud.githubusercontent.com/assets/16014479/25735147/bab4150c-319b-11e7-82c5-b44b007fa21c.PNG)

Problem demo file
[TabmanTableViewProblem.zip](https://github.com/uias/Tabman/files/978600/TabmanTableViewProblem.zip)

thanks

**Comment by FrantisekGazo** [comment]
+1

**Comment by msaps** [comment]
This insetting problem seems to be caused by `automaticallyAdjustsScrollViewInsets`. Setting this to false will prevent this odd behaviour, but then you might have to inset your contents manually. 

A version of Tabman is currently in beta which has automatic insetting behaviour ([0.5.0 Beta 1](https://github.com/uias/Tabman/releases/tag/0.5.0.beta.1)). Please see #43 for further instructions. 

Hoping to get all this insetting stuff really sorted in v0.5.0. 👍

**Comment by hb852143** [comment]
Thanks for your answer !!
