### ISSUE TITLE
Example code seems to be referencing old function names

### ISSUE THREAD

**Issue by GiselleSerate** [uias/Tabman#94]
I noticed that the example code (specifically https://github.com/uias/Tabman/blob/master/Example/Tabman-Example/CustomTabmanBar.swift) is using function names that don't correspond to the superclass. I have the pod in my project on my machine and have looked at the TabmanBar.swift file, where the function names seem to be constructTabBar and addIndicatorToBar instead of construct and add. I think the example code needs to be updated. 
Thank you!

**Comment by msaps** [comment]
Hi,

The functions in `TabmanBar` changed slightly in [`0.5.3`](https://github.com/uias/Tabman/releases/tag/0.5.3) which is why the example code looks out of sync to your project.

If you update your project to use the latest versions of Tabman you should have access to the new functions. They were basically changed to make it easier to build the bar by passing in the `contentView` as a parameter. 😃

**Comment by GiselleSerate** [comment]
Thank you for the prompt response! This worked.
