### ISSUE TITLE
iOS 8 not supported

### ISSUE THREAD

**Issue by farshadmb** [uias/Tabman#96]

**Comment by msaps** [comment]
Please see uias/Pageboy#75.

iOS 8 support has not been added to Tabman due to the development overhead/effort during conception; with the project being designed to support the current and previous versions of iOS at the time (10 & 9). 

The current baseline of iOS 9 will remain when iOS 11 support is fully added.

If you have an iOS 8 capable development environment, please feel free to add support for iOS 8 and submit a PR. 👍

**Comment by farshadmb** [comment]
Hi @msaps 
My Employer forces me to use iOS 8 or Later and I don't find any useful library to reduce my implementation time. How can I do???

**Comment by msaps** [comment]
@farshadmb to make Tabman compatible with iOS 8, you'll have to fork the repo, update the deployment target to `8.0` and then fix any compatibility issues that arise.

**Comment by farshadmb** [comment]
@msaps  My issue that Tabman has Dependency to Other Libraries such as PaperBoy. Should I fork both project?

**Comment by msaps** [comment]
@farshadmb yeah you will have to fork both projects and do the following...

1. Update Pageboy to support iOS 8.
2. Update Tabman `Cartfile` to use your development fork for iOS 8 support.
3. Update Tabman to support iOS 8.
4. Create PR's from both forks into `develop` on the source repo's.

👍

**Comment by farshadmb** [comment]
@msaps Thanks a lot. I don't work a lot with PodRepose file. Could you please provide PR's file for me??

**Comment by msaps** [comment]
@farshadmb  Sorry, by PR I meant a Pull Request back into the main repo. You shouldn't have to mess with any of the pods files. 😄

**Comment by farshadmb** [comment]
@msaps i found another issue with your library 
`appearance.layout.height = .explicit(value:20.0)`
doesn't work. check if contentSize.height bigger than explicit value

**Comment by msaps** [comment]
iOS 8 support is now available as of [0.7.0](https://github.com/uias/Tabman/releases/tag/0.7.0)
